### ISSUE TITLE
Не работает внутренняя навигация между статьями

### ISSUE THREAD

**Issue by ValentinNikin** [yandex-cloud/yfm-docs#451]
Собрал простенький проект из нескольких markdown файлов, согласно https://ydocs.tech/ru/project/.

toc.yaml
```
title: Система контроля качества
href: index.yaml
items:
  - name: Главная страница
    items:
      - name: Обзор
        href: pages/main/common.md
      - name: Боковое меню
        href: pages/main/side-menu.md
      - name: Шапка страницы
        href: pages/main/page-header.md
      - name: Сводка
        href: pages/main/dashboard.md
  - name: Необработанные файлы
    href: pages/pending.md
  - name: Задачи в работе
    href: pages/processing.md
```

Проект успешно генерируется. Но, если генерировать проект под Windows, не работает внутренняя навигация между статьями. См. скриншот ниже

![image](https://github.com/yandex-cloud/yfm-docs/assets/30625611/27c23356-5558-46dc-89e4-9d23dc2700d8)

Сравнил diff-ы полученных документах. Наблюдаю отличие в путях, вероятно с этим связана проблема.
Если генерировать в Windows, то пути получаются такие: "pages\\main\\page-header.html", в Linux такие: "pages/main/page-header.html"
