### ISSUE TITLE
Limit CLI options power

### ISSUE THREAD

**Issue by 3y3** [yandex-cloud/yfm-docs#498]
We have 25 described CLI option. And some not described (like `hidden`, `storage-endpoint`, `storage-bucket`...)
Most of them are complicated and rare useful.

Proposal:
Move rare useful options to `.yfm` config.
Split `.yfm` config on logical parts:
```yaml
build:
  vars:
    - var1: test

publish:
  endpoint: 'https://bucket.tld'

editor:
  hotkeys:
    - some-custom-hotkey: 'alt+c'

viewer:
  logo: 'https://bucket.tld/static/logo.png'
```
